main/routes.py
import os

from flask import Flask, current_app, jsonify, render_template, request, flash, redirect, session, url_for
from werkzeug.utils import secure_filename


from database import db
from main.forms import ApplicationForm, JobPostForm
from main.models import JobApplication, JobPost
from users.routes import manager_required
from google_drive import upload_to_drive

from flask import Blueprint



main = Blueprint('main', __name__)





@main.route('/')
def index():
    # Query the database to get the most recent 3 job openings
    recent_job_openings = JobPost.query.order_by(JobPost.created_at.desc()).limit(3).all()
    google_maps_api_key = current_app.config['GOOGLE_MAPS_API_KEY']

    image_folder = 'indeximages'  # Folder inside 'static'
    image_directory = os.path.join(current_app.static_folder, image_folder)
    # List all jpg and jpeg files
    images = [os.path.join(image_folder, file) for file in os.listdir(image_directory) if file.lower().endswith(('.jpg', '.jpeg'))]
    return render_template('index.html', recent_job_openings=recent_job_openings, google_maps_api_key=google_maps_api_key, images=images)


@main.route('/images')
def images():
    image_directory = os.path.join('static', 'indeximages')
    images = [img for img in os.listdir(image_directory) if img.endswith(('.png', '.jpg', '.jpeg'))]
    return jsonify(images=images)

@main.route('/main/promotion_images')
def promotion_images():
    image_directory = os.path.join('static', 'indexpromotions')
    images = [img for img in os.listdir(image_directory) if img.endswith(('.png', '.jpg', '.jpeg'))]
    return jsonify(images=images)




@main.route('/store_locations')
def store_locations():
    return render_template('store_locations.html')


@main.route('/job_post', methods=['GET', 'POST'])
@manager_required
def job_post():
    form = JobPostForm()
    if form.validate_on_submit():
        job_post = JobPost(
            title=form.title.data,
            company=form.company.data,
            location=form.location.data,
            job_type=form.job_type.data,
            description=form.description.data,
            qualifications=form.qualifications.data
        )
        db.session.add(job_post)
        db.session.commit()
        return redirect(url_for('main.job_post'))
       
    job_posts = JobPost.query.all()
    return render_template('job_post.html', form=form, job_posts=job_posts)


@main.route('/delete_job/<int:id>', methods=['POST'])
def delete_job(id):
    # Retrieve the job opening from the database using the provided ID
    job_post = JobPost.query.get(id)

    if job_post is None:
        # Handle the case where the job opening with the given ID doesn't exist
        flash('Job opening not found.', 'error')
        return redirect(url_for('main.job_post'))

    # Delete the job opening from the database
    db.session.delete(job_post)
    db.session.commit()

    flash('Job opening deleted successfully.', 'success')
    return redirect(url_for('main.job_post'))


# Create a route to render the jobs.html page
@main.route('/jobs')
def job_listings():
    # Query the database to retrieve all job openings
    job_openings = JobPost.query.all()
    
    # Render the jobs.html template and pass the job_openings data
    return render_template('jobs.html', job_openings=job_openings)



@main.route('/apply_job/<int:job_id>', methods=['GET', 'POST'])
def apply_job(job_id):
    # Retrieve the specific job post using its ID
    job_post = JobPost.query.get(job_id)

    # Check if the job post exists
    if job_post is None:
        flash('Job opening not found.', 'error')
        return redirect(url_for('main.job_listings'))

    # Initialize the application form
    form = ApplicationForm()

    # Handle form submission
    if form.validate_on_submit():
        # Extract data from the form
        full_name = form.full_name.data
        email = form.email.data
        phone_number = form.phone_number.data
        education = form.education.data
        experience = form.experience.data
        reference = form.reference.data

        # Process the resume file upload
        resume_file = form.resume.data
        if resume_file:
            # Secure the filename
            filename = secure_filename(resume_file.filename)

            # Google Drive folder ID where resumes will be uploaded
            folder_id = '1HV4J1cBYD7Lo4sy2y4wjll4zM_xo1cko'

            try:
                # Upload the file directly from memory to Google Drive and get the file ID
                file_id = upload_to_drive(resume_file.stream, filename, folder_id)
            except Exception as e:
                # Handle exceptions during file upload
                flash(f'An error occurred while uploading the file to Google Drive: {e}', 'error')
                return render_template('jobapplication.html', job_post=job_post, form=form)

            # Create a new job application record with the Google Drive file ID
            job_application = JobApplication(
                job_post_id=job_id,
                full_name=full_name,
                email=email,
                phone_number=phone_number,
                education=education,
                experience=experience,
                reference=reference,
                resume_filename=file_id  # Storing Google Drive file ID
            )
        else:
            # Create a new job application record without a resume file
            job_application = JobApplication(
                job_post_id=job_id,
                full_name=full_name,
                email=email,
                phone_number=phone_number,
                education=education,
                experience=experience,
                reference=reference
            )

        # Add the new job application to the database
        db.session.add(job_application)
        db.session.commit()

        # Notify the user of successful submission
        flash('Job application submitted successfully!', 'success')
        return redirect(url_for('main.job_listings'))

    # Render the job application form template
    return render_template('jobapplication.html', job_post=job_post, form=form)


@main.route('/trainingvideos')
def trainingvideos():
    return render_template('trainingvideos.html')

users/routes.py
from datetime import datetime
from functools import wraps
import logging
import bcrypt
from flask import  current_app, render_template, request, flash, redirect, session, url_for
from flask_login import LoginManager, current_user, login_user, login_required, logout_user


import os
from dotenv import load_dotenv
from flask_wtf import CSRFProtect
import pytz
from auth import fetch_user_stores, get_user_stores
from users.forms import LoginForm, SettingsForm, SignUpForm

from models import GlobalSettings, Users, Store, ROLES
from database import db


from flask import Blueprint

users = Blueprint('users', __name__)




# Custom decorator to restrict access to owners
def owner_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_authenticated and current_user.user_role == 'Owner':
            return f(*args, **kwargs)
        return redirect(url_for('users.login'))
    return decorated_function

# The manager_required and employee_required decorators can remain as updated above.

# Custom decorator to restrict access to managers
def manager_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_authenticated and current_user.user_role in ['Owner', 'Manager']:
            return f(*args, **kwargs)
        else:
            flash('Access denied. You need manager privileges.', 'danger')
            return redirect(url_for('users.login'))
    return decorated_function

# Custom decorator to restrict access to employees
def employee_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_authenticated and current_user.user_role in ['Employee', 'Manager', 'Owner']:
            return f(*args, **kwargs)
        else:
            flash('Access denied. You need employee privileges.', 'danger')
            return redirect(url_for('users.login'))
    return decorated_function

@users.route('/signup', methods=['GET', 'POST'])
@manager_required
def signup():
    # Create an instance of the SignUpForm
    form = SignUpForm()

    # Fetch all available stores from the 'store_name' table
    # This needs to be done before validating the form to ensure that
    # the 'stores' field in the form has its choices set.
    all_stores = Store.query.all()

    # Set the store choices for the SelectMultipleField
    # This assignment ensures that the form's 'stores' field has the
    # necessary choices available for validation and rendering.
    form.stores.choices = [(store.id, store.name) for store in all_stores]

    # Check if the form has been submitted and is valid
    if form.validate_on_submit():
        # Retrieve data from the form fields
        name = form.name.data
        email = form.email.data
        password = form.password.data
        selected_role = form.role.data
        selected_stores = form.stores.data  # List of selected store IDs

        # Check if the user already exists in the database
        existing_user = Users.query.filter_by(email=email).first()
        if existing_user:
            flash('Email address is already in use. Please use a different email.', 'danger')
            return redirect(url_for('users.signup'))

        # Hash the password before storing it in the database
        hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

        # Create the new user with the assigned role
        new_user = Users(name=name, email=email, password=hashed_password, user_role=selected_role)

        # Associate the selected stores with the new user
        for store_id in selected_stores:
            store = Store.query.get(store_id)
            if store:
                new_user.stores.append(store)

        # Add the user to the database and commit the transaction
        db.session.add(new_user)
        db.session.commit()

        flash('User registration successful!', 'success')
        return redirect(url_for('users.login'))

    # Render the signup form template with the populated form
    return render_template('signup.html', form=form, all_stores=all_stores)


@users.route('/login', methods=['GET', 'POST'])
def login():
    # Create an instance of your login form
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        # Query the user from the database using the provided email
        user = Users.query.filter_by(email=email).first()

        if user and bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
            login_user(user)  # Log in the user using Flask-Login

            flash('Login successful!', 'success')
            return redirect(url_for('terminal.dashboard'))  # Redirect to dashboard upon successful login

        else:
            flash('Login failed. Please check your credentials.', 'danger')

    return render_template('login.html', form=form)

def is_logged_in():
    return 'user_id' in session



@users.route('/logout')
def logout():
    logout_user()
    flash('Logged out successfully.', 'success')
    return redirect(url_for('main.index'))



@users.route('/select_store/<int:store_id>')
@employee_required
def select_store(store_id):
    user = current_user
    user_stores = get_user_stores(user)

    print("Debug: User's stores:", [store.id for store in user_stores])  # Debug print

    if store_id not in [store.id for store in user_stores]:
        flash('You do not have access to this store.', 'danger')
        print("Debug: User does not have access to store ID", store_id)  # Debug print
        return redirect(url_for('terminal.dashboard'))

    try:
        session['selected_store'] = store_id
        user.selected_store_id = store_id
        db.session.commit()
        flash('Store selected successfully!', 'success')
        print("Debug: Store selected:", store_id)  # Debug print
    except Exception as e:
        logging.error(f"Error selecting store for user {user.id}: {e}")
        flash('An error occurred. Please try again.', 'danger')
        print("Debug: Error in selecting store:", e)  # Debug print

    return redirect(url_for('terminal.dashboard'))

# Default TImezone

@users.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingsForm()
    settings_record = GlobalSettings.query.first()

    if form.validate_on_submit():
        if not settings_record:
            settings_record = GlobalSettings()

        settings_record.default_timezone = form.default_timezone.data

        try:
            db.session.add(settings_record)
            db.session.commit()
            flash('Settings updated successfully.', 'success')
        except Exception as e:
            db.session.rollback()
            current_app.logger.error('Failed to update settings: %s', str(e))
            flash(f'Failed to update settings: {e}', 'danger')

        return redirect(url_for('users.settings'))

    elif settings_record:
        form.default_timezone.data = settings_record.default_timezone

    return render_template('settings.html', form=form)

templates/admin_panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>
</head>
<body>
    <div>
        <h1>Welcome to the Admin Panel</h1>
        <p>You've reached the admin view.</p>
    </div>
</body>
</html>

templates/employee.html
{% extends 'base.html' %}

{% block content %}

     <!-- "Welcome" box with employee's name -->
     <div class="highlight-box welcome-box">
        <h1>Welcome, John Doe!</h1>
        <button class="update-button" id="updateInfoButton">Update Info</button>
    </div>
    
        <!-- Form for updating employee information (initially hidden) -->
        <div id="updateInfoForm" style="display: none;">
            <h3>Update Your Information</h3>
            <form>
                <!-- Form fields for updating information -->
                <!-- Add your form fields here -->
                <br>
                <button type="submit">Save Changes</button>
            </form>
        </div>

  <!-- Section 2: Work Schedule and Hours Worked -->
  <div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Employee Name</th>
                <th>Hours Worked</th>
                <th>Store</th>
            </tr>
        </thead>
        <tbody>
            {% for sale in user_daily_sales %}
                <tr>
                    <td>{{ sale.date.strftime('%Y-%m-%d') }}</td>
                    <td>{{ sale.name_employee }}</td> <!-- Adjust based on how you determine the employee's name -->
                    <td>{{ sale.hours_worked }}</td>
                    <td>{{ sale.store }}</td>
                </tr>
            {% endfor %}
        </tbody>
        
    </table>
    
</div>


    <!-- Section 3: Hours Worked -->
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Hours Worked</th>
                    <th>Store Name</th>
                </tr>
            </thead>
            <tbody>
                {% for daily_sale in user_daily_sales.items %}
                <tr>
                    <td>{{ daily_sale.date }}</td>
                    <td>{{ daily_sale.hours_employee }}</td>
                    <td>{{ daily_sale.store.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    






    <!-- Section 4: Payroll Information -->
    <div class="col-md-4">
        <h2>4. Payroll Information</h2>
        <table class="table">
            <tr>
                <th>Hourly Wage</th>
                <td>$15.00</td>
            </tr>
            <tr>
                <th>Overtime Pay</th>
                <td>$22.50</td>
            </tr>
            <tr>
                <th>Bonuses</th>
                <td>$100.00</td>
            </tr>
            <tr>
                <th>Total Earnings</th>
                <td>$1,000.00</td>
            </tr>
        </table>
    </div>


    <!-- Add links to other sections (7, 8, 9, 10, 11) as needed -->

    <p>Additional Sections:</p>
    <ul>
        <li><a href="{{ url_for('main.trainingvideos') }}">Video Library</a></li>
        <li><a href="#">Timekeeping</a></li>
        <li><a href="#">Announcements and News</a></li>
        <li><a href="#">Documents and Forms</a></li>
        <li><a href="#">Contact Information</a></li>
    </ul>

    <p>Other Features:</p>
    <ul>
        <li><a href="#">Employee Directory</a></li>
        <li><a href="#">Training and Resources</a></li>
        <li><a href="#">Performance Metrics</a></li>
    </ul>

    <!-- You can add more content and links here as needed -->

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Homepage - Swing By Home</title>
        <!-- Bootstrap CSS for styling -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
        <style>
            /* Add custom CSS for specific padding on top */
            .custom-padding-top {
                padding-top: 20px; /* Adjust this value as needed */
            }
        </style>
    </head>
    <body>
            <style>
                .image-scroll-box {
                width: 100%;
                overflow: hidden;
                position: relative;
            }

            #rotating-image {
                width: 100%;
                height: auto;
                display: block;
            }

            </style>
                <!-- Top Bar -->
                <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                    <div class="container-fluid">
                        <!-- Navbar brand (optional) -->
                
                        <!-- Toggle button for small screens -->
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        
                        
                
                        <!-- Navbar links -->
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                                <!-- Home Link -->
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                                </li>
                                <!-- Dashboard Link -->
                                <li class="nav-item">
                                    <a class="nav-link" href="/dashboard">Dashboard</a>
                                </li>
                            </ul>
                            
                            <!-- Login/Logout Button -->
                            <div class="d-flex">
                                {% if current_user.is_authenticated %}
                                <!-- Logout Button -->
                                <a class="btn btn-outline-light me-2" href="{{ url_for('users.logout') }}" id="logoutButton">
                                    <i class="fas fa-sign-out-alt"></i>
                                    <span>Logout</span>
                                </a>
                                {% else %}
                                <!-- Login Button -->
                                <a class="btn btn-outline-light" href="{{ url_for('users.login') }}" id="loginButton">
                                    <i class="fas fa-sign-in-alt"></i>
                                    <span>Login</span>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </nav>
                
                
                
                
                
                
               
                
                
                

            <div class="container custom-padding-top">

                <div class="containe ">
                    <div class="row">
                        <!-- Image Slideshow Box -->
                        <div class="col-md-6">
                            <div class="box aspect-ratio-16-9">
                                <div class="image-wrapper">
                                    <!-- Corrected the ID and initial src attribute -->
                                    <img id="rotating-image" src="{{ url_for('static', filename='indeximages/default.jpg') }}" alt="Rotating Image" class="img-fluid">
                                    <!-- Floating banner with a link to main.jobs.html -->
                                    <a href="{{ url_for('main.job_listings') }}" class="floating-banner">
                                        <p>Checkout our products</p>
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                
                        <!-- Placeholder Box for Promotion Content -->
                        <div class="col-md-6">
                            <div class="box aspect-ratio-16-9">
                                <div class="image-wrapper">
                                    <!-- Image with id for JavaScript to target -->
                                    <img id="rotating-promotion-image" src="{{ url_for('static', filename='indexpromotions/default.jpg') }}" alt="Promotion Image" class="img-fluid">
                        
                                    <!-- Floating banner with a link to main.jobs.html -->
                                    <a href="{{ url_for('main.job_listings') }}" class="floating-banner">
                                        <p>Hot Deals!</p>
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <div class="container">
                    <div class="row">
                        <!-- Map Container -->
                        <div class="col-md-6">
                            <div class="box aspect-ratio-16-9">
                                <div class="image-wrapper">
                                    <div id="map"></div>  
                                </div>
                            </div>
                        </div>
                
                        <!-- Image Container -->
                        <div class="col-md-6">
                            <div class="box aspect-ratio-16-9">
                            <div class="image-wrapper">
                                <a href="{{ url_for('main.job_listings') }}">
                                    <img src="{{ url_for('static', filename='joinourteam.jpeg') }}" alt="Join Our Team" class="img-fluid">
                                </a>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
                
                
                
                    <!-- Google Maps Section -->

                    <script src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&libraries=places&callback=initMap" async defer></script>

                    <script>
                        var map;
                        var placesService;
                        var bounds;
                    
                        function initMap() {
                            map = new google.maps.Map(document.getElementById('map'), {
                                center: { lat: 0, lng: 0 }, // This will be updated
                                zoom: 10
                            });
                    
                            placesService = new google.maps.places.PlacesService(map);
                            bounds = new google.maps.LatLngBounds();
                    
                            // Array of your place IDs
                            var placeIDs = [
                                'ChIJ80yny6_5ToYRGp5bsC4VPPo',
                                'ChIJ78MNjrLvToYRtroWlH5gzcU',
                                'ChIJywZlUMNtToYRpRmKAb17RmQ',
                                'ChIJhwKMOWZlToYRST64Mh1Iblk'
                            ];
                    
                            placeIDs.forEach(function(placeID) {
                                addPlaceMarker(placeID);
                            });
                        }
                    
                        function addPlaceMarker(placeID) {
                            placesService.getDetails({
                                placeId: placeID
                            }, function(place, status) {
                                if (status === google.maps.places.PlacesServiceStatus.OK) {
                                    var marker = new google.maps.Marker({
                                        map: map,
                                        position: place.geometry.location
                                    });
                    
                                    var infowindow = new google.maps.InfoWindow({
                                        content: '<div><strong>' + place.name + '</strong><br>' +
                                                place.formatted_address + '</div>'
                                    });
                    
                                    marker.addListener('click', function() {
                                        infowindow.open(map, marker);
                                    });
                    
                                    // Extend the bounds object with each marker's position
                                    bounds.extend(marker.getPosition());
                                    map.fitBounds(bounds); // Adjust the map to fit all markers
                                }
                            });
                        }
                    </script>
                        
                
                <!-- Left Image scroller -->
                <script>
                    var images = [];
                    var currentIndex = 0;
                
                    function rotateImage() {
                        if (currentIndex < images.length) {
                            // Corrected the ID here to match the HTML
                            document.getElementById('rotating-image').src = '{{ url_for("static", filename="") }}' + 'indeximages/' + images[currentIndex];
                            currentIndex++;
                        } else {
                            currentIndex = 0;
                        }
                    }
                
                    fetch('{{ url_for("main.images") }}')
                        .then(response => response.json())
                        .then(data => {
                            images = data.images;
                            rotateImage();
                            setInterval(rotateImage, 5000); // Rotate image every 10 seconds
                        })
                        .catch(error => console.error('Error fetching images:', error));
                </script>
                
                <!-- Right Image scroller -->
                <script>
                    var promotionImages = [];
                    var currentPromotionIndex = 0;
                
                    function rotatePromotionImage() {
                        if (currentPromotionIndex < promotionImages.length) {
                            document.getElementById('rotating-promotion-image').src = '{{ url_for("static", filename="") }}' + 'indexpromotions/' + promotionImages[currentPromotionIndex];
                            currentPromotionIndex++;
                        } else {
                            currentPromotionIndex = 0;
                        }
                    }
                
                    fetch('{{ url_for("main.promotion_images") }}')
                        .then(response => response.json())
                        .then(data => {
                            promotionImages = data.images;
                            rotatePromotionImage();
                            setInterval(rotatePromotionImage, 10000); // Rotate image every 10 seconds
                        })
                        .catch(error => console.error('Error fetching promotion images:', error));
                </script>
                

                

            </div>
    <!-- Bootstrap Bundle with Popper for interactivity -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

templates/jobs.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Job Openings</h1>
    <div class="row">
        {% for job in job_openings %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ job.title }}</h5>
                    <h6 class="text-muted">{{ job.company }}</h6>
                    <p class="card-text mt-3"><strong>Location:</strong> {{ job.location }}</p>
                    <p class="card-text"><strong>Job Type:</strong> {{ job.job_type }}</p>
                    <a href="{{ url_for('main.apply_job', job_id=job.id) }}" class="btn btn-primary">Apply Now</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="highlight-box">
                <h3>Login</h3>

                <form method="POST">
                    {{ form.hidden_tag() }}  <!-- Include CSRF token -->

                    <div class="form-group">
                        {{ form.email.label(class="form-label") }}
                        {{ form.email(class="form-control") }}
                    </div>

                    <div class="form-group">
                        {{ form.password.label(class="form-label") }}
                        {{ form.password(class="form-control") }}
                    </div>

                    <!-- Add more form fields for additional login options if needed -->

                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/misc.html
{% extends 'base.html' %}

{% block content %}


<h1> Checking the sidebar</h1>

{% endblock %}